# Generated by Django 4.2.5 on 2023-09-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_limit', models.IntegerField()),
                ('bath_amount', models.IntegerField()),
                ('pets_allowed', models.BooleanField(default=False)),
                ('cleaning_fee', models.FloatField()),
                ('activated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
