# Generated by Django 4.2.5 on 2023-09-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realties', '0002_realties_active'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='realty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realties.realties'),
        ),
    ]
