# Generated by Django 4.2.5 on 2023-09-22 19:47

from django.db import migrations, models
import django.db.models.deletion
import reservations.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_alter_ads_realty_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=reservations.utils.generate_random_string, editable=False, max_length=8, unique=True)),
                ('guest_amount', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('comment', models.TextField(max_length=1000)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
            ],
        ),
    ]
